name: Build-Docker
on:
  push:
    branches:
      - 'main'

jobs:
  release_job:
    uses: baoduy/ShareWorkflows/.github/workflows/docker-publish.yaml@main
    with:
      dockerFile: "SqlDataCleanup/Dockerfile"
      context: "."
      imageName: "baoduy2412/tool-sql-cleanup"
      platforms: linux/arm64,linux/amd64
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
